# Generated by Django 4.2.3 on 2023-07-17 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('pasport_series', models.CharField(blank=True, max_length=12, verbose_name='Серия паспорта')),
                ('pasport_number', models.CharField(blank=True, max_length=12, verbose_name='Номер паспорта')),
                ('addres', models.CharField(blank=True, max_length=240, verbose_name='Адрес пользователя')),
                ('user_profile_id', models.IntegerField(blank=True, null=True, verbose_name='ID пользователя')),
                ('phone', models.CharField(max_length=24, verbose_name='Телефон')),
                ('uniq_id', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Уникальный ID')),
                ('photo', models.ImageField(blank=True, default='../static/images/default_avatar.png', upload_to='users/%Y/%m/%d/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='super user')),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_of_birthday', models.DateField(blank=True, null=True, verbose_name='Дата Рождения')),
                ('type', models.CharField(choices=[('AD', 'Администратор'), ('DO', 'Врач'), ('CL', 'Клиент'), ('DI', 'Руководитель')], default='CL', max_length=6, verbose_name='Тип пользователя')),
                ('ban', models.BooleanField(default=False, verbose_name='Уволен')),
                ('ban_date', models.DateTimeField(blank=True, null=True, verbose_name='дата увольнения')),
                ('ecp', models.BooleanField(default=False, verbose_name='Наличие ЭЦП')),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='groups', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, null=True, related_name='user_permissions', to='auth.permission', verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='MedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рост')),
                ('weight', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вес')),
                ('blood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа крови')),
                ('age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Возраст')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
    ]
