# Generated by Django 4.2.3 on 2023-07-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_brand_country_type_product_brand_product_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд товара', 'verbose_name_plural': 'Брэнды товаров'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна производитель', 'verbose_name_plural': 'Страны производители'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
